config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :content, :presence => true
  validates :author, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :author, :presence => true
  validates :link, :presence => true

  scope(:rank, -> do
    Post.order(votes: :desc, created_at: :desc)
  end)



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post= Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def show
    @post= Post.all
    @comments = Comment.all
  end

  def create
    @post= Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @post= Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post= Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
      if @comment.update(comment_params)
        redirect_to post_path(@comment.post)
      else
        render :edit
      end
    end

  def destroy
    @post= Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :author)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully added!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :link, :author, :votes)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit this comment:</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Add a comment:</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNewsClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <!-- <%= f.hidden_field :votes %> -->
  <%= f.submit  %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit this post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.rank().each do |post| %>
    <li>
      <%= link_to post.title, post.link %>
      <%= form_for (post) do |f| %>
        <%= f.hidden_field(:votes, :value => post.votes + 1) %>
        <%= f.submit 'upvote' %>
      <% end %>
      <span><%= post.votes %> points</span>
      <%= link_to 'Add a comment', post_path(post) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= link_to 'add comment', new_post_comment_path(@post) %></p>

<% if @post.comments.any? %>
  <h4>Here are the comments for this post:</h4>

  <ul>
    <% @post.comments.each do |comment| %>
    <li>
      <p><%= comment.author %></p>
      <p><%= comment.content %></p>
      <%= link_to "edit comment", edit_post_comment_path(@post, comment) %>
      <%= link_to "delete comment", post_comment_path(@post, comment),
      :data => {:confirm => "Are you sure you want to delete this comment?",
        :method => "delete"} %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments yet!</p>
<% end %>


<p><%= link_to "edit this post", edit_post_path(@post) %></p>

<p><%= link_to "delete this post", post_path(@post),
                                  :data => {:confirm => "Are you sure you want to delete this post?",
                                            :method => "delete"} %></p>

<p><%= link_to "home", posts_path %></p>